import type { Rule, SpineModel } from "../model/spine.js";

export function bullet(rule: Rule): string {
  return `- ${rule.text}`;
}

export function bulletWithTrace(rule: Rule): string {
  return `- ${rule.text} <sup>\`${rule.source.kind}:${rule.source.pointer}\`</sup>`;
}

export function h(level: number, text: string): string {
  return `${"#".repeat(Math.min(Math.max(level, 1), 6))} ${text}`;
}

export function blank(): string {
  return "";
}

export function section(title: string, lines: string[]): string[] {
  if (lines.length === 0) return [];
  return [h(2, title), "", ...lines, ""];
}

export function renderHeader(spine: SpineModel, title: string, intent: string): string[] {
  return [
    h(1, title),
    "",
    `> ${intent}`,
    "",
    `_Generated from \`spine.json\` — hash \`${spine.metadata.hash}\`, project type \`${spine.projectType}\`._`,
    "",
    "<!-- spine:deterministic -->",
    "",
  ];
}

export function renderBlock(rules: Rule[], withTrace = false): string[] {
  if (rules.length === 0) return ["_(none)_"];
  return rules.map(withTrace ? bulletWithTrace : bullet);
}

export function stackLine(spine: SpineModel): string {
  const { stack } = spine;
  const parts: string[] = [];
  if (stack.framework) parts.push(stack.framework);
  if (stack.language) parts.push(stack.language);
  if (stack.styling && stack.styling !== "unknown") parts.push(stack.styling);
  if (stack.testing.length > 0) parts.push(`tests: ${stack.testing.join(", ")}`);
  if (stack.packageManager && stack.packageManager !== "unknown") parts.push(`pm: ${stack.packageManager}`);
  return parts.join(" • ");
}

export function projectPurpose(spine: SpineModel): string {
  const topGoal = spine.goals[0]?.text ?? null;
  const name = spine.metadata.name;
  if (topGoal) return `**${name}** — ${topGoal}`;
  return `**${name}** — project type: ${spine.projectType}.`;
}

export function writtenAt(): string {
  return `<!-- generated by Project Spine; edit \`brief.md\` or rerun \`spine compile\` rather than hand-editing -->`;
}
