import type { RepoProfile } from "../model/repo-profile.js";

export function renderArchitectureSummary(profile: RepoProfile): string {
  const lines: string[] = [];
  lines.push(`# Architecture summary`);
  lines.push("");
  lines.push(`_Generated by Project Spine on ${profile.detectedAt}._`);
  lines.push("");
  lines.push(`## Stack`);
  lines.push("");
  lines.push(`- **Framework:** ${profile.framework.value} _(confidence ${profile.framework.confidence})_`);
  lines.push(`- **Routing:** ${profile.routing.value} _(confidence ${profile.routing.confidence})_`);
  lines.push(`- **Package manager:** ${profile.packageManager.value} _(confidence ${profile.packageManager.confidence})_`);
  lines.push(`- **Language:** ${profile.language.typescript ? `TypeScript${profile.language.strict === true ? " (strict)" : profile.language.strict === false ? " (non-strict)" : ""}` : "JavaScript"}`);
  lines.push(`- **Styling:** ${profile.styling.value} _(confidence ${profile.styling.confidence})_`);
  lines.push("");
  lines.push(`## Testing`);
  lines.push("");
  if (profile.testing.runners.length > 0) {
    lines.push(`- **Runners:** ${profile.testing.runners.join(", ")}`);
  } else {
    lines.push(`- **Runners:** none detected`);
  }
  lines.push(`- **Storybook:** ${profile.testing.storybook ? profile.testing.storybookVersion ?? "present" : "not detected"}`);
  lines.push("");
  lines.push(`## Linting / formatting`);
  lines.push("");
  const lintTools: string[] = [];
  if (profile.linting.eslint) lintTools.push("ESLint");
  if (profile.linting.biome) lintTools.push("Biome");
  if (profile.linting.prettier) lintTools.push("Prettier");
  if (profile.linting.oxlint) lintTools.push("Oxlint");
  lines.push(`- **Tools:** ${lintTools.length > 0 ? lintTools.join(", ") : "none detected"}`);
  lines.push("");
  lines.push(`## CI`);
  lines.push("");
  lines.push(`- **GitHub Actions:** ${profile.ci.githubActions ? `yes (${profile.ci.workflows.length} workflow${profile.ci.workflows.length === 1 ? "" : "s"})` : "no"}`);
  if (profile.ci.other.length > 0) {
    lines.push(`- **Other:** ${profile.ci.other.join(", ")}`);
  }
  lines.push("");
  lines.push(`## Agent files present`);
  lines.push("");
  lines.push(`- AGENTS.md: ${yn(profile.agentFiles.agentsMd)}`);
  lines.push(`- CLAUDE.md: ${yn(profile.agentFiles.claudeMd)}`);
  lines.push(`- .github/copilot-instructions.md: ${yn(profile.agentFiles.copilotInstructions)}`);
  lines.push(`- .cursor/rules/: ${yn(profile.agentFiles.cursorRules)}`);
  lines.push(`- .project-spine/: ${yn(profile.agentFiles.projectSpineDir)}`);
  lines.push("");
  if (profile.warnings.length > 0) {
    lines.push(`## Warnings`);
    lines.push("");
    for (const w of profile.warnings) {
      lines.push(`- **[${w.severity}] ${w.id}** — ${w.message}`);
    }
    lines.push("");
  }
  lines.push(`<!-- spine:deterministic -->`);
  lines.push("");
  return lines.join("\n");
}

function yn(v: boolean): string {
  return v ? "yes" : "no";
}
