#!/usr/bin/env bash
# Regenerate CHANGELOG.md from git tags + commit messages.
#
# Output: Markdown mirror of the GitHub Releases timeline. The site's
# /changelog page pulls from GitHub Releases (canonical); this file is the
# npm-consumer mirror so `npm view project-spine` surfaces it.
#
# Usage:
#   scripts/generate-changelog.sh > CHANGELOG.md
#
# Runs locally and from the release workflow. Zero deps — pure git.
set -euo pipefail

REPO_URL="https://github.com/PetriLahdelma/project-spine"

printf "# Changelog\n\n"
printf "Mirror of the [GitHub Releases](%s/releases) timeline. The site's " "$REPO_URL"
printf "[/changelog](https://projectspine.dev/changelog) page is the canonical human view; "
printf "this file is the npm-consumer mirror, regenerated by \`scripts/generate-changelog.sh\`.\n\n"

# Tags newest-first. Plain read loop for portability (bash 3.x on macOS has
# no mapfile); POSIX-friendly.
TAGS=()
while IFS= read -r line; do
  [ -n "$line" ] && TAGS+=("$line")
done < <(git tag --sort=-v:refname)

# Unreleased section first — anything newer than the latest tag.
if [ "${#TAGS[@]}" -gt 0 ]; then
  LATEST="${TAGS[0]}"
  UNRELEASED="$(git log --pretty=format:"- %s ([\`%h\`](${REPO_URL}/commit/%H))" "${LATEST}..HEAD" || true)"
  if [ -n "$UNRELEASED" ]; then
    printf "## Unreleased\n\n%s\n\n" "$UNRELEASED"
  fi
fi

# For each tag T, list commits reachable from T but not from its predecessor.
for i in "${!TAGS[@]}"; do
  T="${TAGS[$i]}"
  DATE="$(git log -1 --format=%ad --date=short "$T")"
  PREV_INDEX=$((i + 1))
  RANGE_START=""
  if [ "$PREV_INDEX" -lt "${#TAGS[@]}" ]; then
    RANGE_START="${TAGS[$PREV_INDEX]}"
  fi

  printf "## [%s](%s/releases/tag/%s) · %s\n\n" "$T" "$REPO_URL" "$T" "$DATE"
  if [ -n "$RANGE_START" ]; then
    git log --pretty=format:"- %s ([\`%h\`](${REPO_URL}/commit/%H))" "${RANGE_START}..${T}"
  else
    # Oldest tag in the list — dump everything reachable from it.
    git log --pretty=format:"- %s ([\`%h\`](${REPO_URL}/commit/%H))" "${T}"
  fi
  printf "\n\n"
done
